muzei/muzei

android-client-common/build.gradle, build.gradle, example-contract-widget/build.gradle, example-source-500px/build.gradle, example-watchface/build.gradle, main/build.gradle, wearable/build.gradle, web/app.yaml, web/handlers/tasks.py, web/static/archive/archive.js
In order to not touch every build.gradle file every time either the gradle plugin updates or the build tools updates or the newest SDK comes out, we can move all of these values to the main build.gradle file as suggested here: http://tools.android.com/tech-docs/new-build-system/tips
This update also updates the gradle plugin 1.0.0 to 1.0.1 and build tools 21.1.1 to 21.1.2
=> Move Gradle, build tools, and compile/target SDK to main build.gradle

wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java, wearable/src/main/res/values/dimens.xml
Show date on the watch face in MM/dd or dd-MM (locale dependent) format:
- Round: Date is shown above the time (as time is centered on the screen / floating directly above peek card)
- Square: Date is shown below the time (as the time is in the upper right corner)
TODO: Setting to control whether it appears
=> Add date to Android Wear watch face

api/build.gradle, main/src/main/AndroidManifest.xml, wearable/src/main/AndroidManifest.xml
Update Muzei API to build against API 22 and removes no longer needed <meta-data> elements as they are included by default by Google Play services 7.0
=> Version cleanup

wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java
Don't want to call the super method twice.
=> Remove double call to super.onPeekCardPositionUpdate() from watch face

main/src/main/res/values/styles.xml
As of AppCompat 22.1.0, themes that do not want to use an action bar must contain both
<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>
Which is automatically done for us when you extend Theme.AppCompat.NoActionBar. As all of our themes, use a Toolbar and not the provided action bar, we can switch our base theme to Theme.AppCompat.NoActionBar and remove the windowActionBar=false declarations scattered throughout our themes.
=> Moves base theme to Theme.AppCompat.NoActionBar

main/src/main/res/values/wear.xml, wearable/src/main/java/com/google/android/apps/muzei/ActivateMuzeiIntentService.java
Replaces the Wearable.NodeApi.getConnectedNodes() call with a call to Wearable.CapabilityApi.getCapability(), ensuring that only the main app (which has the capability 'activate_muzei') will receive the message to activate Muzei, rather than other Wearable devices or the cloud node.
=> Use the CapabilityApi to send activate messages to the correct node

android-client-common/src/main/java/com/google/android/apps/muzei/util/ImageBlurrer.java, wearable/build.gradle, wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java
Allow tapping on the watchface to toggle between the image and a blurred/dimmed version of the image.
Also updates:
- peek card opacity (transparent when blurred, opaque when not blurred)
- Only use view protection when not blurred
- Shadow behind time/date only shown when not blurred
=> Implement simple blur toggle interactive watch face

wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java
I tested it in emulator by hardcoding a different locale directly in code. Assuming Locale.getDefaultLocale returns the locale as defined by the user.
=> Use locale defined month/date format. e.g. in Germany, this is dd.MM.

main/src/main/java/com/google/android/apps/muzei/WearableController.java
In Google Play services 8.3, DataApi calls may be delayed up to 30 minutes. Calling setUrgent() ensures the wallpaper is updated on the Android Wear side immediately upon being updated on the phone side (subject to connectivity, of course) as explained in the 8.3 blog post: http://android-developers.blogspot.com/2015/11/whats-new-in-google-play-services-83.html
=> Ensure Android Wear wallpaper updates immediately.

main/src/main/java/com/google/android/apps/muzei/util/ScrimUtil.java
I doubt this will make any significant performance improvement since the gradients aren't generated very often, but we use this internally and just wanted to contribute back in case you think it'd be useful!
=> Cache and reuse generated cubic gradient drawables

main/src/main/AndroidManifest.xml, wearable/src/main/AndroidManifest.xml
Watch faces do not need the PROVIDE_BACKGROUND permission nor do they need android:allowEmbedded="true" and android:taskAffinity=""
=> Remove no longer needed PROVIDE_BACKGROUND permission for watch face

main/build.gradle
Per https://developers.google.com/android/guides/releases#june_2016_-_v92
=> Upgrade to Google Play services 9.2.1 to work around ProGuard issue

main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java
When in Preview mode, we don't necessarily want to subscribe/unsubscribe to our current source
=> Ensure we don't subscribe/unsubscribe for preview wallpaper services

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/NetworkChangeReceiver.java
Try to limit network connectivity callbacks to only apps that want network connectivity changes. Even then, don't send network change events to apps on API 24+ that target API 24+ as those apps should be following the behavior changes in API 24 which restrict network change events.
=> Limit Network Connectivity Callbacks

main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/NetworkChangeReceiver.java
Much of the activities that Muzei does should only be done when the wallpaper is active (i.e., the MuzeiWallpaperService is created). This fixes an issue where we wouldn't properly subscribe to sources when in preview mode and Muzei would continue to listen for network changes at all times (even when the wallpaper was disabled!). Now both events are done only when the wallpaper service is created.
=> Tie subscribing and network changes to the wallpaper lifecyle

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java
Instead of keeping a possibly incomplete or a failed file for artwork being written to MuzeiProvider, if we detect an IOException on writing we'll try to delete the artwork file, allowing the other side to retry.
=> Delete artwork being written when an error occurs.

main/src/main/java/com/google/android/apps/muzei/SourceManager.java
SourceManager uses synchronized to manage access to the selected source it maintains. By reducing the amount of code that needs to be in these synchronized blocks, we reduce contention and apparent freezes when changing sources.
=> Reduce SourceManager contention when updating sources

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java
Muzei itself knows how to handle a null artwork just fine, but other apps may not. Ensure that logging remains to help the other apps, but does not occur when it is Muzei itself using the artwork provider
=> Only write helpful Artwork warnings for other apps

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java, main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java
Move notification and Wearable artwork loading to rely solely on MuzeiProvider as source of truth. Instead of tying them into RealRenderController, they are now managed at the MuzeiWallpaperService level.
This also enables adding Source columns to any Artwork query (owing to the join it already does) as well as updates exactly how notification large icons/backgrounds are made - they are no longer square cropped.
=> Use MuzeiProvider as the source for all artwork updates

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, example-contract-widget/src/main/java/com/example/muzei/examplecontractwidget/ArtworkUpdateService.java, example-watchface/src/main/java/com/example/muzei/watchface/ArtworkImageLoader.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableSourceUpdateService.java, wearable/src/main/java/com/google/android/apps/muzei/ActivateMuzeiIntentService.java, wearable/src/main/java/com/google/android/apps/muzei/ArtworkCacheIntentService.java, wearable/src/main/java/com/google/android/apps/muzei/FullScreenActivity.java, wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java, wearable/src/main/java/com/google/android/apps/muzei/SourceChangedListenerService.java, wearable/src/main/java/com/google/android/apps/muzei/util/PanView.java
While getSimpleName() is convenient, it falls apart when using ProGuard, which Muzei uses. Also caught a number of cases where the logging tag was more than the max 23 characters.
=> Remove all instances of Class.getSimpleName() for logging

main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationJobService.java, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationProviderService.java
Fixes issues where
- JobService's started with `addTriggerContentUri` need to be manually rescheduled after they are triggered as per documentation
- Complications falling out of sync with SharedPreferences when uninstalled/reinstalled
- Images being synced to Wear not properly resized down to ~320 pixels
=> Fix complications, Wear image resizing

build.gradle, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
Update to the latest Support Library 24.2.0. Use DiffUtil to build the correct notify() calls for when the Gallery's URIs change
=> Update to Support library 24.2.0

main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkTask.java
Only send a loading=true ArtworkLoadingStateChangedEvent if there is actual loading to be done
=> Only send ArtworkLoadingStateChange with loading=true if load is needed

api/src/main/java/com/google/android/apps/muzei/api/MuzeiArtSource.java, example-contract-widget/build.gradle, example-source-500px/build.gradle, source-featured-art/build.gradle, source-gallery/build.gradle
HandlerThread.quit() will drop pending messages, potentially dropping the final published update as the IntentService is stopped. Switch to API 18's quitSafely() method to ensure any pending publishes are actually done.
=> Ensure MuzeiArtSource publishes prior to being destroyed, min API 18

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiDocumentsProvider.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java
We can safely assume that apps without an android:description on their MuzeiArtSource don't want a description shown (perhaps they are setting it at runtime). Don't crash Muzei in this cases. Fixes GH-165
=> Handle art sources without an android:description

main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/NetworkChangeReceiver.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/TaskQueueService.java, main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkJobService.java, main/src/main/java/com/google/android/apps/muzei/sync/TaskQueueService.java
Instead of retrying whenever the network connectivity changes, use JobScheduler to schedule the retry job and backoff logic.
=> Move artwork retries to use JobScheduler on API 21+

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java
For existing art sources, they did not specify the component name and it needs to be manually added on Muzei's side.
=> Ensure every inserted artwork has a valid component name

main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, source-gallery/src/main/AndroidManifest.xml, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java, source-gallery/src/main/res/menu/gallery_activity.xml, source-gallery/src/main/res/values/strings.xml
Change the default action for adding photos to be `ACTION_OPEN_DOCUMENT` instead of `ACTION_GET_CONTENT`. This allows the Gallery extension to use URI based permissions to read the selected images on demand rather than store a copy of each and every photo selected (which led to a large amount of storage space used for large photo galleries).
In addition, this ensures that photos that are deleted or changed in the source are reflected in the Gallery.
A new menu item is added to the overflow menu that allows users to 'Import Photos' using `ACTION_GET_CONTENT` to support apps still using a `GET_CONTENT` Activity, with a warning of the downsides beforehand.
=> Gallery: Use URI Based Permissions instead of storing a copy when possible

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java, source-gallery/src/main/res/values/strings.xml
The previous workflow for importing photos had a number of downsides:
- The warning dialog felt punitive towards the user even though it wasn't their choice that the app they want to use only supports GET_CONTENT
- The standard Storage Access Framework UI allowed users to import photos that they should really be adding via ACTION_OPEN_DOCUMENT
Since we can query the exact activities supporting GET_CONTENT, we can improve the workflow by:
- Handling only one app by directly starting that Activity
- Handling more than one app by having the user choose which app they want to import photos from
This has the side benefit that there is no need for a scary dialog anymore and photos cannot be imported if adding them directly is an option
=> Improve the workflow for importing photos with GET_CONTENT

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
While I seriously doubt any DocumentsProvider will be providing virtual files that have a mime type of "image/*", better save than sorry (as Muzei does require openable files)
=> Add CATEGORY_OPENABLE to all OPEN_DOCUMENT/GET_CONTENT intents

build.gradle, main/build.gradle, source-featured-art/build.gradle, source-gallery/build.gradle
Upgrade to the latest version of the libraries used. Centralize shared libraries into the top level Gradle file to ease future maintenance.
=> Upgrade to latest build tools, Support Library, and Google Play services

wearable/src/main/java/com/google/android/apps/muzei/FullScreenActivity.java
Long press to exit is no longer suggested for Wear 2.0 devices as per https://developer.android.com/wear/preview/behavior-changes.html#activity-dismissal
=> Disable long press to exit on Wear 2.0 devices

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java
With the changes in loading data, both ARTWORK and ARTWORK_ID URIs are passed to notifyChange(). This fixes ARTWORK_CHANGED broadcasts so that they happen on both types of URIs.
=> Ensure that ACTION_ARTWORK_CHANGED broadcasts work

build.gradle, main/build.gradle
As Renderscript includes native libraries that constitute 45%+ of the total APK size, provide split APKs that only package in exactly the native library that is needed for that device.
=> Split main APKs by ABI

main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/quicksettings/NextArtworkTileService.java
Make it easy for users to quickly go to the next artwork via a quick settings tile. If Muzei is not activated, the tile will offer to activate Muzei.
=> Quick Settings Tile for 'Next Artwork' command

version.properties, wearable/build.gradle
When it comes to publishing Wear 2.0 directly to the Play Store, they must have a separate version code from the phone app to support multiple APKs.
=> Split Wear versioning from phone versioning

main/build.gradle, main/google-services.json, wearable/build.gradle, wearable/google-services.json
Adds Firebase Crash and Firebase Analytics to both the phone/tablet app and the Wear app to allow better measurement of usage.
Only the basics right now: no custom analytics/crash logging
=> Add Firebase Crash+Analytics

android-client-common/build.gradle, build.gradle, example-contract-widget/build.gradle, example-source-500px/build.gradle, example-watchface/build.gradle, main/build.gradle, source-featured-art/build.gradle, source-gallery/build.gradle, wearable/build.gradle
Move the tools and Google Services Gradle plugin versions into the root project. Use the same format for all of them (only keep the version number in the root project).
=> Centralize the Tools and Google Services Plugin versions

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java
The Gallery art source should publish a new artwork if the current artwork is removed. Fixes the logic so that this doesn't force a double load of artwork every time the GalleryArtSource is created.
=> Fix logic on detecting removed Gallery images

main/src/main/res/layout/settings_ab_spinner_list_item.xml
Removes unnecessary LinearLayout from settings_ab_spinner_list_item
=> Removes unnecessary LinearLayout from settings_ab_spinner_list_item

main/build.gradle, main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/PhotoSetAsTargetActivity.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/quicksettings/NextArtworkTileService.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsActivity.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java, wearable/build.gradle, wearable/src/main/AndroidManifest.xml, wearable/src/main/java/com/google/android/apps/muzei/ActivateMuzeiIntentService.java, wearable/src/main/java/com/google/android/apps/muzei/FullScreenActivity.java, wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationProviderService.java
Add analytics around the most important flows such as first time activation, wallpaper and watch face usage, etc.
Added user properties:
- `device_type` to filter Android vs Wear
- `selected_source` to filter analytics/crashes by the current source
=> Add basic analytics and user properties

build.gradle, main/build.gradle
The number of mips and x86 devices is so low that it is not worth specifically supporting those devices with a split APK - the universal APK will allow those devices to continue to work at some expense of increased download size.
=> Reduce number of APKs by using the universal binary for non ARM devices.

main/build.gradle
main release builds will include a wearable release build
main publicBeta builds will include a wearable publicbeta build
=> Ensure build type of embedded Wear apps match main app

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java, version.properties, wearable/proguard-project.txt
Fix crash issues with Muzei 2.3 Beta 1 including
- Race conditions when apps were reading artwork as new artwork was being inserted
- Wear Renderscript/ProGuard issues
- Gallery crashing due to not correctly adding the `IS_TREE_URI` column
Also increments the version code in preparation for Beta 2
=> Fix crashes found in 2.3 Beta 1

example-contract-widget/src/main/java/com/example/muzei/examplecontractwidget/ArtworkUpdateService.java, version.properties, wearable/src/main/AndroidManifest.xml, wearable/src/main/java/com/google/android/apps/muzei/ActivateMuzeiIntentService.java, wearable/src/main/java/com/google/android/apps/muzei/ArtworkCacheIntentService.java
Improve handling of activate/install Muzei notifications when Muzei Wear app is installed without the phone app and disable the complication provider until the first real image is available.
Also improves a long standing issue with example-contract-widget which was preventing testing of the API.
=> Integrate feedback from 2.3 Beta 3: Wearable edge cases

main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkJobService.java
The DownloadArtworkJobService did not properly fire the ArtworkLoadingStateChangedEvent on completion due to a missing super call.
=> Ensure the ArtworkLoadingStateChangedEvent is fired

main/src/main/java/com/google/android/apps/muzei/SourceManager.java
Art Sources can publish updates without attaching artwork, causing Muzei to crash.
=> Fix crash when art sources publish without artwork

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/quicksettings/NextArtworkTileService.java, main/src/main/java/com/google/android/apps/muzei/render/BitmapRegionLoader.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiRendererFragment.java, main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkTask.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
Fixes a number of crashes reported in Muzei 2.3 Beta 3:
- Replaces IllegalStateException on loading artwork with null
- Destroys a no longer used ImageBlurrer
- Only allows BitmapRegionLoaders with a width/height > 0
- Don't crash when you have no active network when activating the wallpaper
- Don't load null artwork URIs
- Fix race condition on updating the quick settings tile
- Prevent Gallery from attempting to animate a detached view
=> Fix crashes reported in 2.3 Beta 3

main/src/main/java/com/google/android/apps/muzei/SourceManager.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Fix crashes and edge cases exposed in Muzei 2.3 Beta 4
- Don't try to migrate data from no longer valid sources from SharedPreferences to MuzeiProvider
- Don't throw `IllegalStateException`s from GalleryProvider since callers are not prepared to handle runtime exceptions
- Catch `SecurityException`s generated by attempting to access no longer valid tree URIs in the Gallery. Now we just remove those URIs (as they are indeed no longer valid)
=> Fix issues found in Muzei 2.3 Beta 4

main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java
Ensure Muzei wallpapers and Wear display images with the correct rotation based on Exif data.
Has the unfortunate side effect for requiring a temporary file prior to Android 7.0 due to ExifInterface only supporting files on earlier versions of Android, but the speed difference is neglibile.
=> Re-add support for rotated images

main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java, main/src/main/java/com/google/android/apps/muzei/PhotoSetAsTargetActivity.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/SourcePackageChangeReceiver.java, main/src/main/java/com/google/android/apps/muzei/SourceSubscriberService.java, main/src/main/java/com/google/android/apps/muzei/quicksettings/NextArtworkTileService.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java
Instead of having a SourceManager singleton managing some shared state, replace it with just a few static methods that get their information from the source of truth: the Sources table in the MuzeiProvider.
This also ensures that we don't have a singleton referencing the application context (which causes issues with Instant Run).
=> Remove the SourceManager Singleton

api/src/main/java/com/google/android/apps/muzei/api/internal/SourceState.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java
Fixes a number of issues
- User property value lengths (actually need to be capped at 36 characters)
- Properly selecting sources
- ExifInterface crashes
- Empty directories for the Gallery extension
- Synchronization issues with SourceState
=> Fix 2.3 beta 4 crashes part 2

main/build.gradle
To prevent cluttering the Firebase Console with crashes for development builds, move the firebase-crash dependency to the "prod" product flavor. This allows us to still build prodDebug builds to test firebase-crash, but allows developers to continue to use devDebug and not bother others with crashes.
=> Disable Firebase Crash Reporting on Dev Builds

main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiRendererFragment.java, main/src/main/java/com/google/android/apps/muzei/util/PanScaleProxyView.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java
Now that the minSdkVersion of Muzei is KitKat, we can remove compat calls and version checks that no longer apply
=> Remove unnecessary API version checks

android-client-common/build.gradle, android-client-common/src/main/AndroidManifest.xml, android-client-common/src/main/java/com/google/android/apps/muzei/provider/DirectBootCacheJobService.java, android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java
Allows Muzei wallpapers to appear while the device is in Direct Boot mode (i.e., before the user has unlocked the device).
Currently this does not take into account user preferences for blurring, dimming, or lock screen specific behavior.
It also assumes that only reading the image is done while in Direct Boot mode. No support for inserts, updates, deletes, or queries until the user is unlocked.
=> Add initial support for Direct Boot

android-client-common/build.gradle, android-client-common/src/main/java/com/google/android/apps/muzei/util/ImageBlurrer.java, build.gradle, main/build.gradle, main/proguard-project.txt, version.properties, wearable/build.gradle, wearable/proguard-project.txt
Since increasing the minSdkVersion, we can now use the framework Renderscript. This should ensure better compatibility, less crashes, and also gives us a much smaller overall APK since we no longer need the Renderscript Support Library's native libraries.
Removed ABI split code as it is no longer necessary.
=> Switch to framework Renderscript

android-client-common/src/main/java/com/google/android/apps/muzei/util/ImageBlurrer.java
Exception java.lang.IllegalStateException: Immutable bitmap passed to Canvas constructor
android.graphics.Canvas.<init> (Canvas.java:150)
com.google.android.apps.muzei.render.MuzeiRendererFragment$1.onBitmapLoaded (MuzeiRendererFragment.java:116)
Caused by creating an immutable Bitmap when blurring. Turns out, there's no benefit from making the Bitmap immutable so making it mutable fixes the problem.
=> Fix MuzeiRendererFragment crash on low memory devices

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
java.lang.IllegalStateException: Cannot start this animator on a detached view!
at android.view.RenderNode.addAnimator(RenderNode.java:812)
at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:55)
at com.google.android.apps.muzei.gallery.GallerySettingsActivity$18$3.run(GallerySettingsActivity.java:896)
Caused by attempting to create a circular reveal on a detached view. Simple enough to not run the animation if the view is detached.
=> Fix GallerySettingsCrash when attempting animation of a detached view

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiDocumentsProvider.java, api/src/main/java/com/google/android/apps/muzei/api/MuzeiContract.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkTask.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java, wearable/src/main/java/com/google/android/apps/muzei/datalayer/ArtworkCacheIntentService.java
With a minSdkVersion of 19, we can use try-with-resources to automatically close Cursors, InputStreams, and OutputStreams instead of needing finally blocks.
=> Use try-with-resources when possible

wearable/build.gradle
Similar to the main app, only enable Crash Reporting on prod builds, ensuring that the Crash Reporting console reflects only issues from real users.
=> Disable Crash Reporting on debug Wear builds

main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, version.properties
With Muzei targeting API 24 now, we cannot use startActivity with Intents that include file:// URIs. Unfortunately, at least one extension sends such view intents. We now catch those errors.
=> Catch FileUriExposedExceptions when starting view intents

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Fixes crashes found in Muzei 2.3 Beta 6:
- Remove invalid artwork View Intents (invalid URIs and file:// URIs)
- Issues persisting permissions for selected Gallery art (causing photo removals, crashes, and artwork info issues)
=> 2.3 Beta6: Fix FileUriExposedException, Gallery Permissions

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Updates to Gradle 3.3 and Tools 2.3.0-beta2 to support development in Android Studio 2.3 Beta 2.
Disables the build cache due to https://code.google.com/p/android/issues/detail?id=229171
=> Update to Gradle 3.3 stable, Tools 2.3.0-beta2, disable build cache

version.properties, wearable/src/main/AndroidManifest.xml
Updates the version code for Beta 7 and sets the Wear app's [standalone flag](https://developer.android.com/wear/preview/features/app-distribution.html#specifying-app-as-standalone) to false as Muzei's Wear app still requires the phone app to load artwork.
=> Prepare for the Beta 7 Release

main/src/main/java/com/google/android/apps/muzei/settings/SettingsAdvancedFragment.java, wearable/build.gradle
Fixes issue where the notification setting was not actually being used, upgrades to Wearable Support Library 2.0.0-beta2 which is the stable version appropriate for pushing to production.
=> Correct notifications, Wearable Support Library

build.gradle, gradle.properties
2.3.0-beta3 fixes https://code.google.com/p/android/issues/detail?id=229171 which allows us to re-enable using the build cache
=> Upgrade to tools 2.3.0-beta3 and re-enable build cache

main/src/main/java/com/google/android/apps/muzei/settings/Prefs.java
Ensure that only one migration is happening simultaneously.
=> Harden notifications migration to device protected storage

main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/render/DemoRenderController.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiRendererFragment.java
Reduces the amount of memory needed by Muzei by
- Fixing a leak of `MuzeiActivity` (the main activity)
- Correctly destroying the `GLPicture`s by ensuring the `MuzeiBlurRenderer`'s `destroy()` method is called before the `GLThread` is finished
- Reducing the number of blur keyframes from 5 to 2 on non-low-RAM devices (reducing the number of pre-computed `GLPicture` instances)
Helps considerably with #31 although the `MuzeiWallpaperService` should be moved to its own process to provide the best memory savings (allowing the rest of the process to be completely removed from memory).
=> Reduce memory usage, fix activity leak

wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationJobService.java, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationProviderService.java
Instead of checking for the count in the ProviderService, check for the existence of a pending job in the JobService. This is more resilient to failures as it keeps the logic on the JobScheduler side rather than trying to track if the job is scheduled separately.
=> Fix complications not updating when there are multiple complications

main/src/main/java/com/google/android/apps/muzei/sync/TaskQueueService.java
On API 24+ devices, we should only re-attempt to download art when the device is not roaming.
=> Artwork downloads should only be rescheduled for not roaming networks

main/build.gradle
As we both product flavors and build types, required the workaround mentioned in here to add a configurations block: https://code.google.com/p/android/issues/detail?id=74658#c43
=> Restrict bundling Wear apps to the prod productFlavor

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Exception java.util.ConcurrentModificationException:
java.util.LinkedHashMap$LinkedHashIterator.remove (LinkedHashMap.java:356)
com.google.android.apps.muzei.gallery.GalleryProvider.applyBatch (GalleryProvider.java:178)
android.content.ContentProvider$Transport.applyBatch (ContentProvider.java:315)
android.content.ContentProviderClient.applyBatch (ContentProviderClient.java:419)
android.content.ContentResolver.applyBatch (ContentResolver.java:1286)
com.google.android.apps.muzei.gallery.GallerySettingsActivity$19.run (GallerySettingsActivity.java:1047)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.os.HandlerThread.run (HandlerThread.java:61)
=> Prevent ConcurrentModificationException when using GalleryProvider

wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationJobService.java
When calling scheduleComplicationUpdateJob from within onStartJob, the job is still marked as pending. This meant that the pending job check made it so that the job was only scheduled once, rather than repeatedly every time the job is started. As JobScheduler automatically replaces pending jobs with the newly scheduled job, there's no downside to scheduling it every time.
=> Remove pending job check from complication scheduling

main/src/main/AndroidManifest.xml
It needs to be exported so that third party launchers can access it. excludeFromRecents and a separate taskAffinity ensure that it is not added to Muzei's task.
=> Fix NextArtworkActivity so that it works correctly

main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.java
Why a widget would be zero pixels in width and height, I don't know, but we shouldn't generate a scaled Bitmap in those cases.
Caused by java.lang.IllegalArgumentException: width and height must be > 0
android.graphics.Bitmap.createBitmap (Bitmap.java:829)
android.graphics.Bitmap.createBitmap (Bitmap.java:808)
android.graphics.Bitmap.createBitmap (Bitmap.java:739)
android.graphics.Bitmap.createScaledBitmap (Bitmap.java:615)
com.google.android.apps.muzei.widget.AppWidgetUpdateTask.scaleBitmap (AppWidgetUpdateTask.java:171)
com.google.android.apps.muzei.widget.AppWidgetUpdateTask.doInBackground (AppWidgetUpdateTask.java:131)
com.google.android.apps.muzei.widget.AppWidgetUpdateTask.doInBackground (AppWidgetUpdateTask.java:52)
android.os.AsyncTask$2.call (AsyncTask.java:295) …
=> Handle widgets of width and height of zero pixels

main/build.gradle, wearable/build.gradle
Add dexOptions.preDexLibraries true and use resConfigs "en" for the dev product flavor.
=> Improve build speeds

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
com.google.android.apps.muzei.gallery.GallerySettingsActivity$19.run (GallerySettingsActivity.java:1042)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.os.HandlerThread.run (HandlerThread.java:61)
=> Fix null Uri passed to GallerySettingsActivity

main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.java
Exception java.lang.IllegalArgumentException: width must be > 0
android.graphics.Bitmap.checkWidthHeight (Bitmap.java:378)
android.graphics.Bitmap.createBitmap (Bitmap.java:684)
android.graphics.Bitmap.createScaledBitmap (Bitmap.java:615)
com.google.android.apps.muzei.render.MuzeiBlurRenderer$GLPictureSet.load (MuzeiBlurRenderer.java:378)
com.google.android.apps.muzei.render.MuzeiBlurRenderer.setAndConsumeBitmapRegionLoader (MuzeiBlurRenderer.java:262)
com.google.android.apps.muzei.render.MuzeiBlurRenderer.onSurfaceCreated (MuzeiBlurRenderer.java:169)
net.rbgrn.android.glwallpaperservice.GLThread.guardedRun (GLWallpaperService.java:662)
net.rbgrn.android.glwallpaperservice.GLThread.run (GLWallpaperService.java:536)
Exception java.lang.IllegalArgumentException: width must be > 0 …
=> Fix crash on zero size Bitmaps in GLPictureSet.load

api/build.gradle, version.properties
Use a separate API code for injecting into the API manifest metadata element.
=> Move API versioning to version.properties, switch to integer

android-client-common/src/main/java/com/google/android/apps/muzei/util/ImageBlurrer.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiRendererFragment.java, wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java, wearable/src/main/java/com/google/android/apps/muzei/util/PanView.java
ImageBlurrer attempts to reuse an Allocation when the Bitmap used to create it was recycled (by MuzeiBlurRenderer). Creating an Allocation wraps the Bitmap, rather than creating a copy so we can create a new Allocation for each new destination Bitmap, preventing reuse abuse.
Moves the source Bitmap input to ImageBlurrer to the constructor to make it clear that there is always one source image (passing in a different image of a different size would have failed anyways). Also fixed an issue where the ScriptIntrinsicColorMatrix was not destroyed.
=> Fix blurring destination Allocation

android-client-common/build.gradle, android-client-common/src/main/AndroidManifest.xml, android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiDocumentsProvider.java, android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Instead of infinitely storing all past artwork, Muzei should only
store the last 10 artwork from each source.
A special exception should be made for artwork that other apps have
persistent access to via the MuzeiDocumentsProvider - those artwork
should never be deleted. Due to how the persistent Uris work on API 25
and lower devices, the Gallery source must manually tell the
MuzeiDocumentsProvider that it is persisting/releasing each URI to avoid
those URIs from being deleted by the MuzeiProvider.
Fixes #383
=> Limit the cache size to 10 images per source + persisted URIs

main/src/main/java/com/google/android/apps/muzei/settings/Prefs.java
moveSharedPreferencesFrom has the unfortunate side effect of requiring
users force stop Muzei (or reboot their device) after the migration
to get their user settings to work again. By moving to our own
migration strategy, we can ensure that upgrading users can instantly
use their current settings.
=> Replace moveSharedPreferencesFrom with our own preference migration

wearable/src/main/java/com/google/android/apps/muzei/util/PanView.java
Done in two parts: excluding images with a zero width or height and
ensuring that the scaled sizes are at least 1 pixel.
Exception java.lang.IllegalArgumentException: width and height must be > 0
android.graphics.Bitmap.createBitmap (Bitmap.java:877)
android.graphics.Bitmap.createBitmap (Bitmap.java:856)
android.graphics.Bitmap.createBitmap (Bitmap.java:787)
android.graphics.Bitmap.createScaledBitmap (Bitmap.java:663)
com.google.android.apps.muzei.util.PanView.updateScaledImage (PanView.java:145)
com.google.android.apps.muzei.util.PanView.setImage (PanView.java:123)
com.google.android.apps.muzei.FullScreenActivity.onLoadFinished (FullScreenActivity.java:211)
com.google.android.apps.muzei.FullScreenActivity.onLoadFinished (FullScreenActivity.java:51) …
=> Fix PanView issues with zero size images

build.gradle, wearable/build.gradle
Upgrade:
- Support Library to 25.3.1
- Google Play services to 10.2.1
- Wearable Support Library to 2.0.1
=> Minor version bump for Support Library, Google Play services, Wearable

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
ContentResolver.call() can fail in many unique ways if we accidentally call it on the wrong ContentProvider. Since it only matters if we're reading from MuzeiDocumentsProvider, we can safely ignore any exceptions that raise from attempting a call().
=> Add generic exception catching around manual persist permission calls

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiDocumentsProvider.java
Tree URIs without documents IDs don't correspond with individual artworks, so we can just ignore them.
Exception java.lang.IllegalArgumentException: Invalid URI: content://com.google.android.apps.muzei.documents/tree/by_date
android.provider.DocumentsContract.getDocumentId (DocumentsContract.java:917)
com.google.android.apps.muzei.provider.MuzeiDocumentsProvider.getArtworkUriForDocumentUri (MuzeiDocumentsProvider.java:132)
com.google.android.apps.muzei.provider.MuzeiDocumentsProvider.call (MuzeiDocumentsProvider.java:191)
android.content.ContentProvider$Transport.call (ContentProvider.java:404)
android.content.ContentResolver.call (ContentResolver.java:1449)
com.google.android.apps.muzei.gallery.GalleryProvider.deleteChosenPhotos (GalleryProvider.java:255) …
=> Handle call() with persisted tree URIs

main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java
Caused by java.lang.NumberFormatException: Invalid int: "????"
java.lang.Integer.invalidInt (Integer.java:138)
java.lang.Integer.parse (Integer.java:410)
java.lang.Integer.parseInt (Integer.java:367)
java.lang.Integer.parseInt (Integer.java:334)
android.support.media.ExifInterface$ExifAttribute.getIntValue (ExifInterface.java:819)
android.support.media.ExifInterface.handleThumbnailFromJfif (ExifInterface.java:2869)
android.support.media.ExifInterface.setThumbnailData (ExifInterface.java:2841)
android.support.media.ExifInterface.loadAttributes (ExifInterface.java:1638)
android.support.media.ExifInterface.<init> (ExifInterface.java:1315)
=> Catch NumberFormatException from ExifInterface

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java
Use the new double[] getLatLong() method instead.
=> Replace deprecated ExifInterface.getLatLong(float[])

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java
We skip trees that error out.
Exception java.lang.NullPointerException: Attempt to get length of null array
android.os.Parcel.readException (Parcel.java:1690)
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:183)
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
android.content.ContentProviderProxy.query (ContentProviderNative.java:421)
android.content.ContentResolver.query (ContentResolver.java:534)
android.content.ContentResolver.query (ContentResolver.java:475)
com.google.android.apps.muzei.gallery.GalleryArtSource.addAllImagesFromTree (GalleryArtSource.java:300)
com.google.android.apps.muzei.gallery.GalleryArtSource.publishNextArtwork (GalleryArtSource.java:193)
com.google.android.apps.muzei.gallery.GalleryArtSource.onUpdate …
=> Fix NPE when adding images from Document Tree URI

main/build.gradle, main/proguard-project.txt, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/shortcuts/ArtworkInfoShortcutController.java, main/src/main/java/com/google/android/apps/muzei/wallpaper/LockscreenObserver.java, main/src/main/java/com/google/android/apps/muzei/wallpaper/NetworkChangeObserver.java, main/src/main/java/com/google/android/apps/muzei/wallpaper/NotificationUpdater.java, main/src/main/java/com/google/android/apps/muzei/wallpaper/WallpaperAnalytics.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java
Instead of having a large block of code in an `initialize()` block for `MuzeiWallpaperService` and a separate `activateWallpaper()` in `MuzeiWallpaperService.MuzeiWallpaperEngine`, take advantage of the [Lifecycle Architecture Component](https://developer.android.com/topic/libraries/architecture/lifecycle.html) to move each piece to separate `LifecycleObserver`s.
=> Use the Lifecycle Architecture Component in MuzeiWallpaperService

android-client-common/build.gradle, api/build.gradle, build.gradle, example-source-500px/build.gradle, example-watchface/build.gradle, gradle.properties, main/build.gradle, source-featured-art/build.gradle, source-gallery/build.gradle, wearable/build.gradle
With the move to Android Studio 3.0 and the [new Android Plugin](https://developer.android.com/studio/preview/features/new-android-plugin.html), a number of [migration steps](https://developer.android.com/studio/preview/features/new-android-plugin-migration.html) were required to get Muzei building from the command line.
=> Ensure Muzei builds from the command line

main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java
Users are very aware that their wallpaper changed (their background changed after all), so badging the Muzei app is unnecessary.
=> Prevent the New Wallpaper notifications from showing a badge by default

main/src/main/java/com/google/android/apps/muzei/ArtDetailFragment.java, main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java, main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java, main/src/main/java/com/google/android/apps/muzei/wallpaper/NotificationUpdater.java, main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.java, main/src/main/java/com/google/android/apps/muzei/widget/WidgetUpdater.java
- Fix a crash when disabling Muzei after a reboot on Android N+ devices
- Ensure that the notification stays in sync with Muzei and is only shown when Muzei is active
- Hide the 'Next' button from the widget when Muzei is not active
=> Improve integrations with the service's lifecycle

build.gradle, gradle/wrapper/gradle-wrapper.properties, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
When forcing a folder, we should pick an image from that folder to force, rather than try to force the tree URI itself.
We now use the token of the artwork as the chosen photo URI: this allows us to correctly swap to another image when the folder is removed.
=> Fix Gallery deletion/force logic for folders

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, api/src/main/java/com/google/android/apps/muzei/api/MuzeiContract.java, main/src/main/java/com/google/android/apps/muzei/PhotoSetAsTargetActivity.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Update the GalleryProvider and MuzeiProvider to better handle error cases without crashing Muzei. Namely, removing the use of SQLExceptions entirely and handling SecurityExceptions when fetching gallery image metadata.
=> Better exception handling from ContentProviders

main/src/main/res/drawable-v25/ic_shortcut_artwork_info.xml, main/src/main/res/drawable-v25/ic_shortcut_background.xml
Rather than rely on each shortcut to add the inset, bake it into the background drawable itself.
=> Move inset of API 25 app shortcuts into the background itself

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java
Rather than create a new instance of Random every time a new photo needs to be chosen, use a static Random instance, mirroring the approach used by the Featured Art source.
=> Use a static Random for the Gallery

build.gradle
Fixes crashes when using FontCompat 26.0.0 as described in
https://developer.android.com/topic/libraries/support-library/revisions.html#26-0-1
=> Update Support Library to 26.0.1

api/src/main/java/com/google/android/apps/muzei/api/Artwork.java, api/src/main/java/com/google/android/apps/muzei/api/MuzeiContract.java, main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkTask.java
Maybe someone(like me) want to develop a Muzei source that provide a set of images, we can let Muzei support the resources artwork.
With doing that, in `MuzeiArtSource.onUpdate`, we can publish an artwork with image uri in a format of `android.resource://<packageName>/<resourceType>/<resourceEntryName>` or `android.resource://<packageName>/<resourceId>`.
=> Support "android.resource" type artwork

main/src/main/java/com/google/android/apps/muzei/SourceManager.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java, main/src/main/res/values/strings.xml
The current Muzei API does not support targeting API 26 (on either Muzei
or the source's side). With source's potentially targeting API 26 without
testing their Muzei integrations, Muzei should defensively switch away
from those sources and warn users that they are unable to use that
source.
Does some minor Lint fixing of the SettingsChooseSourceFragment as well.
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=com.backdrops.wallpapers/.muzei.ArtSource (has extras) }: app is in background uid null
android.app.ContextImpl.startServiceCommon (ContextImpl.java:1505)
android.app.ContextImpl.startService (ContextImpl.java:1461)
android.content.ContextWrapper.startService (ContextWrapper.java:644) …
=> Fix issues when sources target API 26

build.gradle, main/build.gradle, wearable/build.gradle
- Lifecycle to 1.0.0-alpha9
- Google Play services to 11.2.0
- Wearable to 2.0.4
And switches us to use google() for the repository name and centralizes
all versions to the root build.gradle file.
=> Update library versions

source-gallery/build.gradle, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryImportPhotosDialogFragment.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsViewModel.java
Have the Import Photos dialog and the Gallery Settings Activity share
the same list of GET_CONTENT activities by moving the loading and
retrieval to a shared ViewModel.
Also fixes lingering Lint warnings in GallerySettingsActivity.
=> Use a shared ViewModel+LiveData for Gallery Settings + Import Dialog

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
Updates logic to correctly resize images to smaller only if there is more than one image for a ChosenPhoto.
=> Fix Gallery image sizes

android-client-common/build.gradle, api/build.gradle, build.gradle, example-source-500px/build.gradle, example-watchface/build.gradle, main/build.gradle, source-featured-art/build.gradle, source-gallery/build.gradle, wearable/build.gradle
Remove no longer required buildToolsVersion field as per
https://androidstudio.googleblog.com/2017/10/android-studio-30-beta-7-is-now.html
=> Update to Android plugin 3.0.0-beta7

main/src/main/java/com/google/android/apps/muzei/SourceSubscriberService.java
In cases where a source moves from supporting 'Next Artwork' to not supporting it, make sure the Source is also updated.
=> Fix supportsNextArtwork

main/src/main/java/com/google/android/apps/muzei/render/BitmapRegionLoader.java
Renderscript does not support RGBA_F16 images as might be decoded from JPEG images with an embedded color profile on API 26+ devices. By having BitmapRegionLoader always set the inPreferredConfig to ARGB_8888, we ensure that the resulting images can work with Renderscript.
Exception android.renderscript.RSInvalidStateException: Bad bitmap type: RGBA_F16
android.renderscript.Allocation.elementFromBitmap (Allocation.java:2767)
android.renderscript.Allocation.typeFromBitmap (Allocation.java:2772)
android.renderscript.Allocation.createFromBitmap (Allocation.java:2811)
android.renderscript.Allocation.createFromBitmap (Allocation.java:3063)
com.google.android.apps.muzei.util.ImageBlurrer.<init> (ImageBlurrer.java:43)
com.google.android.apps.muzei.render.MuzeiBlurRenderer$GLPictureSet.load …
=> Ensure decoded images are presented in ARGB_8888, not RGBA_F16

api/src/main/java/com/google/android/apps/muzei/api/RemoteMuzeiArtSource.java
Previously, the exponential backoff provided by RetryException only applies in cases where the network wasn't connected. Update the contract so that we'll also exponentially back off if onTryUpdate throws a RetryException.
This helps in cases such as #493
=> Allow onTryUpdate throwing RetryException to increment retry attempts

main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.java
Widgets are limited to ~1.5x the screen size in memory and that's big enough for our needs.
Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
Caused by java.lang.IllegalArgumentException: RemoteViews for widget update exceeds maximum bitmap memory usage (used: 12916836, max: 12441600)
android.os.Parcel.readException (Parcel.java:1688)
android.os.Parcel.readException (Parcel.java:1637)
com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds (IAppWidgetService.java:647)
android.appwidget.AppWidgetManager.updateAppWidget (AppWidgetManager.java:474)
android.appwidget.AppWidgetManager.updateAppWidget (AppWidgetManager.java:547)
com.google.android.apps.muzei.widget.AppWidgetUpdateTask.doInBackground (AppWidgetUpdateTask.java:146) …
=> Restrict widget image's size to the screen size

android-client-common/src/main/res/values/colors.xml, main/src/main/java/com/google/android/apps/muzei/ArtDetailFragment.java, main/src/main/java/com/google/android/apps/muzei/MainFragment.java, main/src/main/java/com/google/android/apps/muzei/MuzeiActivity.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsActivity.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsAdvancedFragment.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java, main/src/main/java/com/google/android/apps/muzei/util/SmartInsetLinearLayout.java, main/src/main/res/drawable/ic_main_choose_source.xml, main/src/main/res/drawable/ic_main_effects.xml, main/src/main/res/layout-sw600dp/settings_advanced_fragment.xml, main/src/main/res/layout-v21/main_fragment.xml, main/src/main/res/layout/art_detail_fragment.xml, main/src/main/res/layout/main_fragment.xml, main/src/main/res/layout/settings_advanced_fragment.xml, main/src/main/res/layout/settings_choose_source_fragment.xml, main/src/main/res/menu/main.xml, main/src/main/res/menu/muzei_overflow.xml, main/src/main/res/values/strings.xml
Expose all of the main functionality of Muzei on a global bottom nav:
- Muzei (the main art details screen that Muzei already starts on)
- Sources (the Sources settings screen)
- Effects (the 'Advanced' settings screen)
Tapping on the art details screen not only hides the art details information, but also the bottom nav, retaining the full screen view of the artwork. Tapping on the Muzei bottom navigation button when it is already selected also triggers the full screen view.
This replaces the existing method of reaching the Sources and Effects screens via the 'Customize' option in the overflow menu on the art details screen. The SettingsActivity that contains the Sources/Effects screen is still in use as the configuration activity for setting the wallpaper, but is otherwise not …
=> Move Muzei to using Bottom Nav

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java
MuzeiProvider incorrectly still attempted to return the sources._id column, which doesn't exist anymore. This caused issues with other apps, such as [Action Launcher](https://play.google.com/store/apps/details?id=com.actionlauncher.playstore), that were attempting to query Muzei to get the current wallpaper.
=> Fix querying MuzeiProvider

main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.kt
Instead of using an effective minimum width of 1.15 of the screen's width, only zoom images if absolutely required to avoid black bars on the sides of the screen. This then allows artwork of the exact size of the screen to fit without scrolling.
Fixes #409
=> Only zoom images if needed to fill the screen size

build.gradle, main/src/main/java/com/google/android/apps/muzei/MainFragment.kt, main/src/main/res/values/styles.xml
When Muzei goes to full screen, allow the wallpaper to display around any display cutouts.
Fixes #522
=> Update to Support Library 28.0.0-alpha3, add support for display cutouts

android-client-common/src/main/res/values/colors.xml, build.gradle, main/build.gradle, main/src/main/java/com/google/android/apps/muzei/ChooseProviderFragment.kt, main/src/main/java/com/google/android/apps/muzei/browse/BrowseProviderFragment.kt, main/src/main/java/com/google/android/apps/muzei/browse/BrowseProviderViewModel.kt, main/src/main/res/layout/browse_provider_fragment.xml, main/src/main/res/layout/browse_provider_item.xml, main/src/main/res/layout/choose_provider_fragment.xml, main/src/main/res/navigation/main_navigation.xml, main/src/main/res/values-w600dp/integers.xml, main/src/main/res/values-w960dp/integers.xml, main/src/main/res/values/colors.xml, main/src/main/res/values/integers.xml, main/src/main/res/values/strings.xml
Add a new 'Browse' action for each selected provider that allows users to browse through all of the artwork a provider has loaded and set the current wallpaper to any wallpaper.
Fixes #486
=> Allow users to browse artwork and set the wallpaper

main/src/main/java/com/google/android/apps/muzei/ArtDetailFragment.kt, main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.kt, main/src/main/java/com/google/android/apps/muzei/settings/GesturesFragment.kt, main/src/main/java/com/google/android/apps/muzei/settings/Prefs.kt, main/src/main/res/layout/gestures_fragment.xml, main/src/main/res/menu/muzei_overflow.xml, main/src/main/res/navigation/main_navigation.xml, main/src/main/res/values/strings.xml
Instead of only having a fixed action (temporarily disabling effects) on one gesture (double tap), expand the set of gestures and actions that Muzei supports out of the box to include:
- Both double tap and three finger tap gestures
- Temporarily disable effects, next artwork, view artwork details, or none as available actions
=> Add settings to customize gestures

muzei-api/src/main/java/com/google/android/apps/muzei/api/internal/RecentArtworkIdsConverter.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java
Ensure there's no duplicates in the recent artwork id list by removing any existing ids when adding a new id. This avoids unnecessary cache misses due to removeAutoCachedFile being called too early.
Fixes #556
=> Treat recent artwork ids as a set

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderContract.java
Since the _ID auto-increments, it is a unique indicator or the last added artwork.
Fixes #555
=> Use the _ID to determine the last loaded artwork

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, version.properties
Avoid doing a full update (and the subsequent notifyChange()) if nothing actually changed. This removes cases where there's just a single image and it is unconditionally changed every time onLoadRequested() is called, causing an infinite loading loop.
When developers specifically call update(), we always call notifyChange() in case they are sorting by DATE_MODIFIED and want an updated list.
Fixes #559
=> Only do a full update() from addArtwork() if something changed

android-client-common/src/main/java/com/google/android/apps/muzei/sync/ArtworkLoadWorker.kt, android-client-common/src/main/java/com/google/android/apps/muzei/sync/ProviderChangedWorker.kt, muzei-api/src/main/java/com/google/android/apps/muzei/api/internal/ProtocolConstants.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java
Instead of silently ignoring invalid artwork (artwork that cannot be loaded by Muzei due to image format issues), we send a signal to the MuzeiArtProvider so that it can delete its invalid artwork.
Fixes #564
=> Inform MuzeiArtProviders about invalid artwork

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java
Ensure that we use the correct ID when doing an update to an existing artwork in response to an insert.
Fixes #566
=> Fix insert of an artwork with an existing token

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderContract.java
When a MuzeiArtProvider is disabled, you cannot access its content URI in any meaningful way (every request will instantly fail). Ensure that ProviderContract.Artwork.getContentUri() only returns non-disabled providers.
=> Don't return content URIs for disabled MuzeiArtProviders

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java
Use setStrict(true) to prevent possible SQL injection issues when MuzeiArtProviders don't use the permission or during automated Google Play Store testing (which don't take the permission into account).
Fixes #577
=> Prevent SQL Injection into MuzeiArtProvider.query

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java
When the cache is cleared, the directory MuzeiArtProvider stores cached artwork in is deleted, causing FileOutputStream to fail when re-downloading the file. By ensuring that the cache directory is created before calling FileOutputStream, we can redownload artwork lost when the cache was cleared.
=> Ensure MuzeiArtProviders recover from the cache being cleared

android-client-common/src/main/java/com/google/android/apps/muzei/sync/ArtworkLoadWorker.kt, android-client-common/src/main/java/com/google/android/apps/muzei/sync/ProviderChangedWorker.kt, android-client-common/src/main/java/com/google/android/apps/muzei/util/ContentProviderClientCompat.kt
Parcel.writeException details a set of RuntimeExceptions that are sent over to the calling app. If a MuzeiArtProvider threw any of these RuntimeExceptions, they'd crash Muzei - we want to avoid that by catching all of these exceptions and rethrowing them as RemoteException, which Muzei uses as the signal that the remote MuzeiArtProvider crashed.
Special handling was added around checking for valid artwork to ensure the now RemoteExceptions don't take down the entire Worker, but instead are captured locally and mark the artwork as invalid.
Fixes #581
=> Ensure MuzeiArtProviders cannot crash Muzei

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtProvider.kt
When the image is already cached, `openFile(Artwork)` is never called. While that's totally fine for loading the image, in some cases, the MuzeiArtProvider might not know if an image is still valid until right when it is loaded (i.e., the source image could have been deleted).
Add a isArtworkValid method that is called by openFile(Uri, String) to give MuzeiArtProviders the hook needed to invalidate images that are already cached.
=> Adds a way to intercept openFile calls even if the image is cached

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java
Rather than relying on ArtworkLoadWorker to call onInvalidArtwork, call it directly in cases where isArtworkValid returns false. This ensures that the Artwork is cleaned up when the file is opened for different purposes (i.e., from the BrowseFragment).
=> Call onInvalidArtwork when isArtworkValid returns false

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtProvider.kt
Instead of making the default implementation of openFile(Artwork) artificially limited to only IOExceptions and SecurityExceptions, have openFile(Artwork) throw any exception (as is common for content:// URIs).
Call onInvalidArtwork whenever a non-IOException is thrown.
=> Catch all exceptions from openFile(Artwork)

android-client-common/src/main/java/com/google/android/apps/muzei/sync/ArtworkLoadWorker.kt, android-client-common/src/main/java/com/google/android/apps/muzei/sync/ProviderChangedWorker.kt, android-client-common/src/main/java/com/google/android/apps/muzei/sync/ProviderManager.kt, example-unsplash/src/main/java/com/example/muzei/unsplash/UnsplashExampleWorker.kt, main/src/main/java/com/google/android/apps/muzei/ChooseProviderFragment.kt, main/src/main/java/com/google/android/apps/muzei/sources/SourceSubscriberService.kt, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/Artwork.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderClient.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderContract.java, source-featured-art/src/main/java/com/google/android/apps/muzei/featuredart/FeaturedArtWorker.kt, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/ChosenPhotoDao.kt, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryScanWorker.kt, source-single/src/main/java/com/google/android/apps/muzei/single/SingleArtProvider.kt, source-single/src/main/java/com/google/android/apps/muzei/single/SingleSettingsActivity.kt, wearable/src/main/java/com/google/android/apps/muzei/datalayer/DataLayerLoadWorker.kt
Instead of keeping a duplicate of each static method in ProviderClient (one using a Class and another using an authority String), create a new interface called ProviderClient that encapsulates all of the static methods.
MuzeiArtProvider itself implements ProviderClient, while instances can be created from new static methods on ProviderContract.
=> Move static methods in ProviderContract.Artwork to ProviderClient

example-unsplash/src/main/java/com/example/muzei/unsplash/UnsplashExampleWorker.kt, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderClient.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderContract.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryScanWorker.kt
Rather than inserting each Artwork one at a time, allow MuzeiArtProvider developers to bulk insert Artwork.
=> Provide an addArtwork API that takes multiple Artwork

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderClient.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderContract.java
Rather than having MuzeiArtProvider developers bulk insert artwork and then have to manually diff their MuzeiArtProvider to delete no longer valid artwork, provide a setArtwork method that takes multiple artwork.
Provides an easy mechanism to handle the problem in #584
=> Provide an setArtwork API that takes multiple Artwork

android-client-common/src/main/java/com/google/android/apps/muzei/room/ArtworkExt.kt, main/src/main/java/com/google/android/apps/muzei/sources/SourceArtProvider.kt, muzei-api/src/main/java/com/google/android/apps/muzei/api/internal/ProtocolConstants.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/Artwork.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtProvider.kt, source-single/src/main/java/com/google/android/apps/muzei/single/SingleArtProvider.kt, version.properties
Instead of having MuzeiArtProviders directly call startActivity from the background (which is restricted on Android Q), provide a separate getArtworkInfo() API that allows a MuzeiArtProvider to give Muzei a PendingIntent for it to launch.
Fixes #604
=> Replace openArtworkInfo() with getArtworkInfo()

legacy-standalone/src/main/java/com/google/android/apps/muzei/legacy/SourceArtProvider.kt
Instead of instantiating a new OkHttpClient every time openFile() is called with an http or https URI, create just a single instance.
Fixes #607
=> Only instantiate one OkHttpClient

main/src/main/java/com/google/android/apps/muzei/ChooseProviderFragment.kt, main/src/main/java/com/google/android/apps/muzei/legacy/LegacySourceInfoFragment.kt, main/src/main/java/com/google/android/apps/muzei/legacy/LegacySourceManager.kt, main/src/main/java/com/google/android/apps/muzei/legacy/LegacySourcePackageListener.kt, main/src/main/res/layout-w540dp/legacy_source_info_fragment.xml, main/src/main/res/layout/legacy_source_info_fragment.xml, main/src/main/res/layout/legacy_source_info_item.xml, main/src/main/res/menu/legacy_source_info_fragment.xml, main/src/main/res/navigation/main_navigation.xml, main/src/main/res/values/dimens.xml, main/src/main/res/values/strings.xml
Let users get a list of legacy sources they have installed with links to the app info screen for each along with a link to Google Play to send the developer of the legacy source feedback.
Fixes #615
=> Add a Legacy Source Info screen

main/src/main/java/com/google/android/apps/muzei/ArtDetailFragment.kt
Instead of showing an empty space where the title or byline would be, hide the empty TextView entirely.
Fixes #622
=> Hide title and byline fields when they are empty

android-client-common/src/main/res/values/strings.xml, example-unsplash/src/main/res/values/strings.xml, example-watchface/src/main/res/values/strings.xml, legacy-standalone/src/main/res/values-v23/strings.xml, legacy-standalone/src/main/res/values/strings.xml, main/src/main/res/values/strings.xml, source-gallery/src/main/res/values/strings.xml
Add translatable="false" and <xliff:g> tags to strings and sections of strings that should not be translated due to being proper nouns or control characters.
For #647
=> Prepare strings.xml files for translation

android-client-common/src/main/java/com/google/android/apps/muzei/sync/ProviderManager.kt, wearable/build.gradle, wearable/src/main/java/com/google/android/apps/muzei/MuzeiActivity.kt, wearable/src/main/java/com/google/android/apps/muzei/MuzeiArtworkItem.kt, wearable/src/main/java/com/google/android/apps/muzei/MuzeiCommandItem.kt, wearable/src/main/java/com/google/android/apps/muzei/MuzeiNextArtworkItem.kt, wearable/src/main/java/com/google/android/apps/muzei/MuzeiProviderItem.kt, wearable/src/main/res/layout/muzei_activity.xml, wearable/src/main/res/layout/muzei_artwork_item.xml, wearable/src/main/res/layout/muzei_command_item.xml, wearable/src/main/res/layout/muzei_next_artwork_item.xml, wearable/src/main/res/layout/muzei_provider_item.xml, wearable/src/main/res/values/dimens.xml
Rather than only showing a single command for local sources installed on Wear OS devices, show all commands, sorting the ones with `shouldShowAsIcon()` above other commands.
As part of this, restructured the content of `MuzeiActivity` into four separate `RecyclerView.Adapter` instances:
- Artwork
- Next Artwork
- Commands
- Provider
And use `MergeAdapter` to bring all of them together into one `RecyclerView`.
=> Show multiple commands on Wear OS devices

main/src/main/res/layout/art_detail_fragment.xml, main/src/main/res/values-sw600dp/dimens.xml, main/src/main/res/values/dimens.xml
Simplify the attribution, title, and byline margins to better support all combinations of attribution, title, and byline. Specifically, fixing cases where only the title is empty or where everything but the attribution is empty.
Fixes a regression from #622
=> Don't use negative margins for title and attribution

example-unsplash/build.gradle, example-unsplash/src/main/AndroidManifest.xml, example-unsplash/src/main/java/com/example/muzei/unsplash/UnsplashRedirectActivity.kt, example-unsplash/src/main/res/values-v29/bools.xml, example-unsplash/src/main/res/values/bools.xml, example-unsplash/src/main/res/values/strings.xml, main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/ChooseProviderFragment.kt, main/src/main/res/navigation/main_navigation.xml, muzei-api/build.gradle, muzei-api/src/main/java/com/google/android/apps/muzei/api/MuzeiContract.kt
The `createChooseProviderIntent()` method adds an official API for deep linking into Muzei's Sources screen, automatically scrolling to the provided `MuzeiArtProvider`.
Provided an example of how the Unsplash example source could use this to redirect users to Muzei's Sources screen from its launcher icon on API 29+ devices.
Fixes #659
=> Create an Intent for deep linking into Muzei's Sources screen

main/src/main/res/layout/effects_screen_fragment_include_content.xml, main/src/main/res/values/dimens.xml
Ensure that none of the titles appear partially offscreen. Also adds a small padding between the titles and SeekBars to ensure that they are readable.
Fixes #667
=> Fix Effects SeekBar titles being truncated

main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.kt, main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.kt
Allow Muzei to react to the zoom level changing on Android 11 devices. This means that Muzei will zoom in slightly (20%) when the notification shade is pulled down or (at least when using the Pixel Launcher) when the app drawer is pulled up.
Fixes #681
=> Implement Android 11's onZoomChanged()

main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.kt, main/src/main/java/com/google/android/apps/muzei/render/RenderController.kt
Rather than slowly transition to the lock screen effects, make the transition immediate. This avoids cases where the user quickly unlocks their device (i.e., via fingerprint / face unlock) and they see two transitions back to back.
This does not change the transition back to the home screen effects - that still transitions smoothly from the lock screen effects.
Fixes #554
=> Immediately switch to lock screen effects

main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.kt, main/src/main/java/com/google/android/apps/muzei/render/MuzeiBlurRenderer.kt
Rather than start the image all the way zoomed out and zoom in when the notification shade, etc. is opened, start the image slightly zoomed in and zoom out.
Switch the zoom percentage to 10% maximum.
Fixes #691
=> Switch zoom direction and lower zoom percentage

main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.kt
We are using cropCenter in layout. 
But cropping happens on a low quality image, this produces pixlized images when widget is landscape and image is portrait for example. 
So, do an initial square cropping before sending image to widget
=> Fix over pixelized images in widget

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.kt
Without this, Muzei plugins that target API 31 and when run on Android 12.0+ cannot view artwork information, instead returning an `IllegalArgumentException` described [here](https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent)
An API level check is included to maintain compatability with Android versions lower than M
=> Specify PendingIntent mutability in getArtworkInfo() within MuzeiArtProvider

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.kt
Maintain readers-writer locks to handle concurrency in
`openFile(Uri, String)`.
See also: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html
Fixes #708
=> Prevent concurrent writes to artwork's cache

source-featured-art/src/main/java/com/google/android/apps/muzei/featuredart/FeaturedArtWorker.kt
Should behave exactly the same, but allows us to swap GCP projects if needed.
=> Switch API endpoint to muzei.co
