build.gradle, main/build.gradle, wearable/build.gradle
Uses [Elvis Operators](http://groovy.codehaus.org/Operators#Operators-ElvisOperator(?:)) on signing config properties as they can no longer be null.
=> Update to Gradle Plugin 1.1.0

main/build.gradle, main/proguard-project.txt, wearable/build.gradle, wearable/proguard-project.txt
Removes ProGuard configurations as they are now automatically included as part of the Google Play services AAR as per https://plus.google.com/+IanLake/posts/1HfDuFFkMXG
=> Update to Google Play services 7.0

build.gradle, main/build.gradle, wearable/build.gradle
Updates Support Library to 22.2.0, Gradle plugin to 1.2.3, compile SDK version to 22, build tools to 22.0.1, and Google Play services to 7.5.0
=> Update dependencies to latest versions

wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java, wearable/src/main/res/values/dimens.xml
Fixes issues with date display including the shadow on round devices, recent changes in density, and hiding the date when there isn't enough vertical space (such as when there are very tall peek cards)
=> Date fixes

main/src/main/java/com/google/android/apps/muzei/util/SvgPathParser.java
Add support for quadratic Bezier curves through Q and q commands in SVG Path parser.
=> Support for quadratic Bezier curves.

build.gradle
Android Studio 2.2 Preview 5 requires 2.2.0-alpha5.
=> Upgrade to Gradle plugin 2.2.0-alpha5

wearable/src/main/java/com/google/android/apps/muzei/MuzeiWatchFace.java
=> Remove the deprecated Time class from the watchface

android-client-common/build.gradle, build.gradle, example-contract-widget/build.gradle, example-source-500px/build.gradle, example-watchface/build.gradle, main/build.gradle, source-featured-art/build.gradle, source-gallery/build.gradle, wearable/build.gradle
Move to a centralized Support Library version and upgrade to version 24.1.1
=> Upgrade Support Library to 24.1.1

wearable/src/main/java/com/google/android/apps/muzei/ArtworkCacheIntentService.java
MuzeiProvider openOutputStream() will return null if it has already cached the artwork. We need to make sure ArtworkCacheIntentService is aware of that and handles that case correctly (i.e., don't attempt to write it again).
=> Ensure ArtworkCacheIntentService handles receiving the same artwork

wearable/build.gradle, wearable/src/main/AndroidManifest.xml, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationBootReceiver.java, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationJobService.java, wearable/src/main/java/com/google/android/apps/muzei/complications/ArtworkComplicationProviderService.java, wearable/src/main/res/values/strings.xml
Allow other watch faces to use Muzei artwork as the background of their watch face
=> Add a LARGE_IMAGE Artwork Complication to the Wear app

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, wearable/src/main/java/com/google/android/apps/muzei/ArtworkCacheIntentService.java
Fix two issues associated with syncing to wear. Namely, assuming the ComponentName for a source is always valid (not true with a phone synced to Wear source info) and handling the race case where the artwork row syncs before the source row syncs, leading to an issue with the foreign key constraint we have set up.
=> Fix issues syncing to Wear

build.gradle
To support development in Android Studio 2.2 Beta
=> Update to Gradle Plugin 2.2.0-beta1

build.gradle
To support development in Android Studio 2.2 Beta 3
=> Update to Gradle Plugin 2.2.0-beta3

build.gradle
To support building in Android Studio 2.2 RC
=> Upgrade to Gradle Plugin 2.2.0-rc1

build.gradle
To support development in the now stable Android Studio 2.2
=> Upgrade to Gradle Plugin 2.2.0

main/build.gradle, wearable/build.gradle
Firebase needs an explicit applicationId for manifest merging
=> Add missing applicationId needed for Firebase

gradle.properties
Per https://medium.com/google-developers/faster-android-studio-builds-with-dex-in-process-5988ed8aa37e
=> Enable Dex in Process + Daemon

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Work around issues where checkCallingUriPermission returns false for tree URIs from other apps.
=> Ensure that tree URI permissions are persisted

build.gradle
Upgrade to latest Android Gradle plugin, Support Library, and Google Play services
=> Version Upgrades

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java
Ensure that every artwork insert, source insert, and source update is valid.
=> Harden the MuzeiProvider against incorrect data/invalid usage

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, api/src/main/java/com/google/android/apps/muzei/api/Artwork.java
Fix two additional crash issues found in Beta 4:
- Concurrent modification exceptions when applying batch operations
- Uri.parse failing when unmarshalling an Artwork object out of a Cursor
=> Fix crash issues with Beta 4

build.gradle, main/build.gradle, main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java, main/src/main/res/values/strings.xml, main/src/main/res/xml/wallpaper.xml, source-gallery/build.gradle, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java, wearable/build.gradle, wearable/src/main/java/com/google/android/apps/muzei/datalayer/ActivateMuzeiIntentService.java, wearable/src/main/res/values/strings.xml
Upgrade to
- Support Library 25.1.0 (implement ExifInterface Support Library)
- Wearable Support Library 2.0.0-beta1 (implement open Play Store on phone action)
- Build tools 25.0.2
- okhttp 3.5.0
- Google Play services/Firebase 10.0.1 (Firebase Crash reporting out of beta!)
- targetSdkVersion to 25 (remove resizing of MuzeiActivity, add wallpaper.info context fields)
=> Upgrade to latest versions of everything

main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java
Instead of only using the ID, also use the image URI and token if available. This prevents cases where the source republishes the same artwork again (causing a new ID, but the same image URI/token) and bothering the user with yet another notification that they already dismissed
=> Use image URI and token for notification dismissal

main/src/main/java/com/google/android/apps/muzei/render/RealRenderController.java, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java
android.support.media.ExifInterface.readImageFileDirectory (ExifInterface.java:2618)
android.support.media.ExifInterface.readImageFileDirectory (ExifInterface.java:2795)
android.support.media.ExifInterface.readImageFileDirectory (ExifInterface.java:2795)
android.support.media.ExifInterface.readImageFileDirectory (ExifInterface.java:2795)
=> Handle StackOverflowErrors associated with ExifInterface

main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java
=> Only animate settings cog when the visibility is changing

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/PhotoSetAsTargetActivity.java, main/src/main/java/com/google/android/apps/muzei/SourceSubscriberService.java, main/src/main/java/com/google/android/apps/muzei/quicksettings/NextArtworkTileService.java, main/src/main/java/com/google/android/apps/muzei/render/RenderController.java, main/src/main/java/com/google/android/apps/muzei/settings/AboutActivity.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java, source-gallery/src/main/res/values/strings.xml
Fix all outstanding crashes reported in Muzei 2.3
=> Fix crashes found in Muzei 2.3

android-client-common/src/main/java/com/google/android/apps/muzei/provider/DirectBootCacheJobService.java, main/src/main/java/com/google/android/apps/muzei/render/RenderController.java, main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateReceiver.java, main/src/main/java/com/google/android/apps/muzei/widget/MuzeiAppWidgetProvider.java
Ensure that multiple AsyncTasks can run concurrently
=> Move AsyncTasks to proper Executors

main/build.gradle, main/src/main/AndroidManifest.xml, main/src/main/java/com/google/android/apps/muzei/tasker/TaskerActionReceiver.java, main/src/main/java/com/google/android/apps/muzei/tasker/TaskerSettingActivity.java
As per the Tasker documentation: http://www.twofortyfouram.com/developer
=> Adds a Tasker plugin to trigger the 'Next Artwork' action

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
Exception java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=image/* cmp=com.lostpixels.fieldservice/com.ipaulpro.afilechooser.FileChooserActivity (has extras) } from ProcessRecord{95a0d2c 17019:net.nurik.roman.muzei/u0a160} (pid=17019, uid=10160) not exported from uid 10118
android.os.Parcel.readException (Parcel.java:1620)
android.os.Parcel.readException (Parcel.java:1573)
android.app.ActivityManagerProxy.startActivity (ActivityManagerNative.java:2707)
android.app.Instrumentation.execStartActivity (Instrumentation.java:1574)
android.app.Activity.startActivityForResult (Activity.java:3933)
android.support.v4.app.BaseFragmentActivityJB.startActivityForResult (BaseFragmentActivityJB.java:50) …
=> Gallery: Hide GET_CONTENT activities that aren't exported/don't have permission

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Exception java.lang.IllegalArgumentException: can't open file: /storage/744C-65EA/Capas/Streets-wallpaper-10596780.jpg
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:165)
android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel (DatabaseUtils.java:146)
android.content.ContentProviderProxy.openTypedAssetFile (ContentProviderNative.java:692)
android.content.ContentResolver.openTypedAssetFileDescriptor (ContentResolver.java:1107)
android.content.ContentResolver.openAssetFileDescriptor (ContentResolver.java:944)
android.content.ContentResolver.openFileDescriptor (ContentResolver.java:797)
android.content.ContentResolver.openFileDescriptor (ContentResolver.java:751)
com.google.android.apps.muzei.gallery.GalleryProvider.openFileChosenPhoto …
=> Gallery: Catch IllegalArgumentExceptions when attempting to open files

version.properties
Main only push of Muzei 2.3 Beta 4 (Wear has not changed)
=> Update versions for Muzei 2.3 Beta 4

main/src/main/java/com/google/android/apps/muzei/settings/AboutActivity.java
Exception java.lang.NullPointerException:
com.google.android.apps.muzei.settings.AboutActivity$3.run (AboutActivity.java:118)
android.os.Handler.handleCallback (Handler.java:808)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5322)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:829)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:645)
dalvik.system.NativeStart.main (NativeStart.java)
=> Fix About Logo NPE

main/src/main/AndroidManifest.xml
As per https://android-developers.googleblog.com/2017/03/update-your-app-to-take-advantage-of.html
=> Support long aspect ratio devices

main/src/main/java/com/google/android/apps/muzei/settings/AboutActivity.java
Simplifies the logic of obtaining the version name.
=> Obtain version name through BuildConfig

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java
Now just output a single line when artwork is removed from the cache
=> Remove overly chatty logging

build.gradle, main/build.gradle, main/src/debug/AndroidManifest.xml, wearable/build.gradle, wearable/src/debug/AndroidManifest.xml
Disables Firebase Perf in debug builds
=> Add Firebase Perf

build.gradle, main/build.gradle, version.properties, wearable/build.gradle
Update Gradle Plugin, Wearable Support Library, and remove no longer needed product flavors
=> Gradle updates

main/src/main/java/com/google/android/apps/muzei/PhotoSetAsTargetActivity.java, main/src/main/java/com/google/android/apps/muzei/sync/DownloadArtworkTask.java, main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.java, main/src/main/res/values/dimens.xml, main/src/main/res/values/strings.xml, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryArtSource.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryProvider.java
Fix a number of crashes in Muzei 2.3.1
=> Crash fixes for Muzei 2.3.1

build.gradle, main/src/main/java/com/google/android/apps/muzei/NewWallpaperNotificationReceiver.java, main/src/main/res/values/strings.xml, wearable/src/main/java/com/google/android/apps/muzei/datalayer/ActivateMuzeiIntentService.java, wearable/src/main/res/values/strings.xml
As per https://developer.android.com/preview/features/notification-channels.html
=> Update notifications to use Notification Channels

main/src/main/java/com/google/android/apps/muzei/shortcuts/ArtworkInfoShortcutController.java
Need to actually register the ContentObserver.
=> Ensure the Artwork Info Shortcut is updated

main/src/main/java/com/google/android/apps/muzei/render/ImageUtil.java, main/src/main/java/com/google/android/apps/muzei/settings/SettingsChooseSourceFragment.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySetupActivity.java, version.properties
Fixes for Beta 2 in preparation for Beta 3
=> Fix 2.3.2 beta2

main/build.gradle, main/proguard-project.txt
Remove no longer needed proguard rules
=> Update to Lifecycle 1.0.0-alpha4

android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiProvider.java, main/src/main/java/com/google/android/apps/muzei/render/MuzeiRendererFragment.java, main/src/main/java/com/google/android/apps/muzei/render/RenderController.java, version.properties
Fix issues discovered in Muzei 2.3.2 RC 1, update version code for RC 2
=> Fix 2.3.2 rc1

version.properties
Update to avoid building against Canary 6
Avoid crashes due to AAPT and vector drawables crashing on API 19 devices.
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f080058
android.content.res.Resources.getValue (Resources.java:1131)
android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates (AppCompatDrawableManager.java:330)
android.support.v7.widget.AppCompatDrawableManager.getDrawable (AppCompatDrawableManager.java:195)
android.support.v7.widget.AppCompatDrawableManager.getDrawable (AppCompatDrawableManager.java:188)
android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup (AppCompatDrawableManager.java:755)
android.support.v7.widget.AppCompatDrawableManager.getDrawable (AppCompatDrawableManager.java:193) …
=> Update version code for Muzei 2.3.2 RC 3

build.gradle
For use with Android Studio 3.0 Canary 8
=> Update Gradle plugin to 3.0.0-alpha8

build.gradle
Fixes https://issuetracker.google.com/issues/38419426
=> Update firebase-plugins to 1.1.1

source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GalleryImportPhotosDialogFragment.java, source-gallery/src/main/java/com/google/android/apps/muzei/gallery/GallerySettingsActivity.java
@ianhanniballake could you review? I have run into this problem couple of times so I decided to fix it.
=> Stop dismissing 'Import photo from' dialog on rotations

build.gradle, version.properties
Wearable 2.0.4 is bad and should feel bad.
Exception java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/wearable/watchface/IWatchFaceService$Stub;
android.support.wearable.watchface.WatchFaceService$Engine.onSetBinder (WatchFaceService.java:459)
android.support.wearable.watchface.WatchFaceService$Engine.onCommand (WatchFaceService.java:426)
android.service.wallpaper.WallpaperService$Engine.doCommand (WallpaperService.java:977)
android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage (WallpaperService.java:1191)
com.android.internal.os.HandlerCaller$MyHandler.handleMessage (HandlerCaller.java:37)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main …
=> Fix Wearable crashes

android-client-common/schemas/com.google.android.apps.muzei.room.MuzeiDatabase/5.json, android-client-common/src/main/java/com/google/android/apps/muzei/room/MuzeiDatabase.java, build.gradle
- Build tools
- Architecture Components
- Google Play services
- Wearable Library
- okhttp
=> Update versions of everything

main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.java
Allow the launcher to query for the current artwork's colors and notify any active listeners when the artwork changes.
=> Implement the WallpaperColors API for O_MR1 devices

main/src/main/java/com/google/android/apps/muzei/notifications/NewWallpaperNotificationReceiver.java, main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.java
Use the rotation information to ensure that the images in the widget and notification large icon / Android Wear background are properly rotated.
Fixes #505
=> Properly rotate widget and notification image

build.gradle, main/src/main/java/com/google/android/apps/muzei/wearable/WearableController.java, wearable/src/main/java/com/google/android/apps/muzei/datalayer/ActivateMuzeiIntentService.java, wearable/src/main/java/com/google/android/apps/muzei/datalayer/ArtworkCacheIntentService.java
Replace deprecated GoogleApiClient based Wearable APIs with the new GoogleApi based solutions
=> Update to Google Play services 11.8.0, move to Wear GoogleApi

main/src/main/java/com/google/android/apps/muzei/widget/AppWidgetUpdateTask.java
Continuously reduce the size of the app widget image until it fits under the maximum bitmap memory usage limit, which apparently is too low for some devices.
Caused by java.lang.IllegalArgumentException
RemoteViews for widget update exceeds maximum bitmap memory usage (used: 13003236, max: 12441600)
arrow_right
android.os.Parcel.readException (Parcel.java:1688)
android.os.Parcel.readException (Parcel.java:1637)
com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds (IAppWidgetService.java:647)
android.appwidget.AppWidgetManager.updateAppWidget (AppWidgetManager.java:474)
android.appwidget.AppWidgetManager.updateAppWidget (AppWidgetManager.java:547)
com.google.android.apps.muzei.widget.AppWidgetUpdateTask.doInBackground (AppWidgetUpdateTask.java:139) …
=> Automatically retry updateAppWidget if maximum bitmap memory usage exceeded

build.gradle, main/build.gradle, main/src/main/java/com/google/android/apps/muzei/MainFragment.kt, main/src/main/res/layout-v21/main_fragment.xml, main/src/main/res/layout/main_fragment.xml, main/src/main/res/navigation/main_navigation.xml
Replace our custom code for handling MainFragment's BottomNavigationView with Navigation.
=> Use the Navigation Architecture Component for MainFragment

README.md
500px example was removed in 44bdb3192722fb66f3690a0ba7482f2e33228746
=> fix link - 500px example -> Unsplash example

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.java, muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/ProviderContract.java
=> Add applyBatch and bulkInsert support to MuzeiArtProvider

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/Artwork.java
Provide a more useful toString() method for Artwork to aid in debugging.
=> Override Artwork.toString()

main/src/main/java/com/google/android/apps/muzei/legacy/LegacySourcePackageListener.kt
Instead of sending a notification for every Legacy Source every time the set of Legacy Sources change, only send a notification once per source. Users can now open Muzei to get information about all of the installed Legacy Sources, rather than rely on the notifications alone.
As a consequence, there will be cases where the summary notification shows the total number of legacy sources, despite there only being only the subset of new sources being shown as notifications.
Fixes #619
=> Only send Legacy Source notifications for new sources

muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtProvider.kt
Adjust logging in MuzeiArtProvider to fall under two categories:
- Verbose logging for the communications between Muzei and the MuzeiArtProvider
- Info logging for exceptions that are handled internally by the MuzeiArtProvider
#623
=> Respect Log.isLoggable() for all MuzeiArtProvider logging

main/src/main/java/com/google/android/apps/muzei/browse/BrowseProviderFragment.kt
Bring up a context menu when long pressing an image on the 'Browse' screen that allows users to select custom commands.
Fixes #595
=> Allow long press on the 'Browse' screen to trigger custom commands

build.gradle, muzei-api/build.gradle
Updated some libraries versions
=> Update androidx.core, firebase, activityVersion, pagingVersion

build.gradle, example-watchface/build.gradle, example-watchface/src/main/java/com/example/muzei/watchface/MuzeiExampleWatchface.kt
Update the `MuzeiExampleWatchface` to use the new `wear-watchface` APIs.
=> Switch the example-watchface to the wear-watchface APIs
